[constants]
# TODO: change to suitable directory path
wolfssl_prefix = '/home/randolph/opt/luckfox-wolfssl/current'
boost_prefix = '/home/randolph/opt/luckfox-boost/current'
toolchain_prefix = '/home/randolph/opt/luckfox-pico/bin/arm-rockchip830-linux-uclibcgnueabihf-'

[binaries]
readelf = toolchain_prefix + 'readelf'
size    = toolchain_prefix + 'size'
strings = toolchain_prefix + 'strings'
c       = toolchain_prefix + 'gcc'
cpp     = toolchain_prefix + 'g++'
ar      = toolchain_prefix + 'ar'
strip   = toolchain_prefix + 'strip'
nm      = toolchain_prefix + 'nm'
objcopy = toolchain_prefix + 'objcopy'
objdump = toolchain_prefix + 'objdump'
ranlib  = toolchain_prefix + 'ranlib'
pkg-config = 'pkg-config'

# RV1106 => ARMv7-A
[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7'
endian = 'little'

[built-in options]
c_args = ['-march=armv7-a', '-mtune=cortex-a7', '-mfpu=neon-vfpv4', '-mfloat-abi=hard', '-I' + wolfssl_prefix / 'include/wolfssl']
cpp_args = ['-march=armv7-a', '-mtune=cortex-a7', '-mfpu=neon-vfpv4', '-mfloat-abi=hard', '-std=c++17', '-I' + wolfssl_prefix /  'include/wolfssl']

pkg_config_path = [boost_prefix / 'lib/pkgconfig', wolfssl_prefix / 'lib/pkgconfig']

# Optional linker flags if needed
c_link_args = []
cpp_link_args = []

# Force C++17 project-wide
cpp_std = 'c++17'


[properties]
boost_root = boost_prefix
