[binaries]
c = 'arm-rockchip830-linux-uclibcgnueabihf-gcc'
cpp = 'arm-rockchip830-linux-uclibcgnueabihf-g++'
ar = 'arm-rockchip830-linux-uclibcgnueabihf-ar'
strip = 'arm-rockchip830-linux-uclibcgnueabihf-strip'
pkg-config = 'pkg-config'

# RV1106 => ARMv7-A
[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'armv7'
endian = 'little'

# optional: if you want to run target binaries via qemu-arm-static
[properties]
needs_exe_wrapper = true
sys_root = '$HOME/luckfox-pico/tools/linux/toolchain/arm-rockchip830-linux-uclibcgnueabihf/arm-rockchip830-linux-uclibcgnueabihf/sysroot'

[built-in options]
c_args = ['-march=armv7-a', '-mtune=cortex-a7', '-mfpu=neon-vfpv4', '-mfloat-abi=hard']
cpp_args = ['-march=armv7-a', '-mtune=cortex-a7', '-mfpu=neon-vfpv4', '-mfloat-abi=hard', '-std=c++17']

# Optional linker flags if needed
c_link_args = []
cpp_link_args = []

# Force C++17 project-wide
cpp_std = 'c++17'
